name: pytest
description: "action that runs pytest"

inputs:
  python_version:
    description: 'Run with python version'
    required: false
    default: "3.11"
  codecov_token:
    description: 'Code Cov token stored in GitHub Secrets'
    required: true

runs:
  using: "composite"

  steps:

    - name: Set up Python ${{ inputs.python_version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ inputs.python_version }}

    - name: Install dependencies
      shell: bash
      run: |
        sudo python -m pip install --upgrade pip
        sudo pip install -r requirements.txt

    - name: Analysing the code with Pytest
      shell: bash
      run: |
        sudo pytest --cov=./ --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ inputs.codecov_token }}
        file: ./coverage.xml
