name: flake8

inputs:
  python_version:
    description: 'Run with python version'
    type: string
    required: false
    default: "3.11"

runs:
  using: "composite"
  steps:
#    - uses: actions/checkout@v3

    - name: Set up Python ${{ input.python_version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ input.python_version }}

    - name: Install dependencies
      run: |
        sudo python -m pip install --upgrade pip
        sudo pip install -r requirements.txt

    - name: Run flake8
      run: >
        sudo flake8 ./src/hostsmate ./src/utils
        --max-complexity 10
        --max-line-length 88
        --benchmark -v
