name: Code Validation

on:
  push:
    branches:
      - develop
      - master
    paths-ignore:
      - ".github/*"

  pull_request:
    branches: [ master, develop]
    types:
      - opened
      - edited
      - closed
    paths:
      - "src/*"

  workflow_dispatch:
    inputs:
      python_version:
        description: 'Run with python version'
        type: string
        required: false
        default: "3.11"

permissions:
  contents: read

jobs:
  pytest:
    name: PyTest Workflow
    env:
      python_version: "3.11"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python ${{ inputs.python_version }} Environment
        uses: owlleg6/hostsmate/.github/actions/python_setup@cicd/flake8-workflow
        with:
          python_version: ${{ inputs.python_version || env.python_version }}

      - name: PyTest Code Coverage
        uses: owlleg6/hostsmate/.github/actions/pytest@cicd/flake8-workflow
        with:
          codecov_token: ${{ secrets.CODECOV_TOKEN }}

  flake8:
    name: Flake8 Workflow
    env:
      python_version: "3.11"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python ${{ inputs.python_version || env.python_version }} Environment
        uses: owlleg6/hostsmate/.github/actions/python_setup@cicd/flake8-workflow
        with:
          python_version: ${{ inputs.python_version }}

      - name: Flake8 Code Analysis
        uses: owlleg6/hostsmate/.github/actions/flake8@cicd/flake8-workflow


  #pytest:
  #  name: Run PyTest
  #  runs-on: ubuntu-latest
  #  permissions:
  #    contents: read
  #  env:
  #    PYTHON_VERSION: "3.11"
  #  uses: owlleg6/hostsmate/.github/workflows/pytest.yml@cicd/flake8-workflow
  #  #with:
  #  #  python_version: "3.11" #${{ inputs.python_version || env.PYTHON_VERSION }}

  #flake8:
  #  name: Run Flake8
  #  runs-on: ubuntu-latest
  #  permissions:
  #    contents: read
  #  env:
  #    PYTHON_VERSION: "3.11"
  #  uses: owlleg6/hostsmate/.github/workflows/flake8.yml@cicd/flake8-workflow
  #  #with:
  #  #  python_version: "3.11"#${{ inputs.python_version || env.PYTHON_VERSION }}
