name: Code Validation

on:
  push:
    branches:
      - develop
      - master
    paths-ignore:
      - ".github/*"

  pull_request:
    branches: [ master, develop]
    types:
      - opened
      - edited
      - closed
    paths:
      - "src/*"

  workflow_dispatch:
    inputs:
      python_version:
        description: 'Run with python version'
        type: string
        required: false
        default: "3.11"

permissions:
  contents: read

jobs:
  pytest:
    name: Run PyTest
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      PYTHON_VERSION: "3.11"
    uses: owlleg6/hostsmate/.github/workflows/pytest.yml@cicd/flake8-workflow
    #with:
    #  python_version: "3.11" #${{ inputs.python_version || env.PYTHON_VERSION }}

  flake8:
    name: Run Flake8
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      PYTHON_VERSION: "3.11"
    uses: owlleg6/hostsmate/.github/workflows/flake8.yml@cicd/flake8-workflow
    #with:
    #  python_version: "3.11"#${{ inputs.python_version || env.PYTHON_VERSION }}
