name: flake8

on:
  push:
  pull_request:
    branches:
      - develop
    paths:
      - "src/hostsmate/*"
      - "src/utils/*"

  workflow_dispatch:
    inputs:
      python_version:
        description: 'Run with python version'
        type: string
        required: false
        default: "3.11"

jobs:
  flake8:
    runs-on: ubuntu-latest
    env:
      python_version: "3.11"

    steps:
      - uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.python_version }}

      - name: Install dependencies
        run: |
          sudo python -m pip install --upgrade pip
          sudo pip install -r requirements.txt

      - name: Run flake8
        run: |
          sudo flake8 src/hostsmate/ --max-complexity 10 --max-line-length 88
          sudo ls -la
