name: Flake8

on:
  workflow_call:
    inputs:
      python_version:
        description: 'Run with python version'
        type: string
        required: false
        default: "3.11"
  workflow_dispatch:
    inputs:
      python_version:
        description: 'Run with python version'
        type: string
        required: false
        default: "3.11"

jobs:
  flake8:
    name: Flake8 Workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python ${{ inputs.python_version }} Environment
        uses: owlleg6/hostsmate/.github/actions/python_setup@cicd/flake8-workflow
        with:
          python_version: ${{ inputs.python_version }}

      - name: Flake8 Code Analysis
        uses: owlleg6/hostsmate/.github/actions/flake8@cicd/flake8-workflow
