name: Pylint

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo python -m pip install --upgrade pip
        sudo pip install -r requirements.txt
        sudo pip install pylint
    - name: Analysing the code with pylint
      run: |
        sudo pylint $(git ls-files '*.py')
